"""Per-file complexity report.

For every .cs file under Assets/Scripts, compute:

  * LOC                        — total lines
  * SLOC                       — non-blank, non-comment-only lines
  * Methods                    — count of `access-modifier T Name(...)` lines
  * Cyclomatic-ish branches    — sum of `if|else|foreach|for|while|case` tokens
  * Max nesting                — max indentation depth of `if`/`for`/`while`
  * Switch-arm count           — `case ` lines
  * String allocations         — estimates of `string +`, `string.Format`,
                                  `StringBuilder` usage

Output: `docs/COMPLEXITY.md`. Sorted descending by SLOC.
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ASSETS = REPO_ROOT / "Assets"
DOCS = REPO_ROOT / "docs"
DOCS.mkdir(exist_ok=True)

PROD_DIRS = [ASSETS / "Scripts"]


def strip_comments(text: str) -> str:
    text = re.sub(r"//.*$", "", text, flags=re.MULTILINE)
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    return text


def complexity(text: str) -> dict[str, int]:
    stripped = strip_comments(text)
    lines = text.splitlines()
    sloc_lines = [ln for ln in stripped.splitlines() if ln.strip()]

    methods = len(re.findall(r"\b(?:public|private|internal|protected|static)\s+[A-Za-z_][A-Za-z0-9_<>?,\s]*\s+[A-Z][A-Za-z0-9_]+\s*\(", stripped))
    branches = sum(stripped.count(tok) for tok in (" if ", " if(", " else ", " for ", " foreach ", " while ", " case "))
    switches = stripped.count(" switch ")
    if_blocks = stripped.count(" if ")
    max_nest = 0
    for line in lines:
        if re.search(r"\b(if|for|while|foreach)\b", line):
            indent = len(line) - len(line.lstrip())
            max_nest = max(max_nest, indent)

    return {
        "lines": len(lines),
        "sloc": len(sloc_lines),
        "methods": methods,
        "branches": branches,
        "switches": switches,
        "if_blocks": if_blocks,
        "max_nesting_indent": max_nest,
    }


def main() -> int:
    rows: list[tuple[Path, dict[str, int]]] = []
    for root in PROD_DIRS:
        if not root.exists():
            continue
        for cs in root.rglob("*.cs"):
            try:
                text = cs.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            rows.append((cs, complexity(text)))

    rows.sort(key=lambda r: r[1]["sloc"], reverse=True)

    lines = [
        "# Complexity Report",
        "",
        "_Generated by Tools/audit_complexity.py — heuristic only. Numbers are SLOC-weighted._",
        "",
        "| File | LOC | SLOC | Methods | Branches | Switches | If Blocks | Max Nest |",
        "|------|-----|------|---------|----------|----------|-----------|----------|",
    ]
    for path, c in rows:
        rel = path.relative_to(REPO_ROOT)
        lines.append(
            f"| `{rel}` | {c['lines']} | {c['sloc']} | {c['methods']} | "
            f"{c['branches']} | {c['switches']} | {c['if_blocks']} | "
            f"{c['max_nesting_indent']} |"
        )

    out = DOCS / "COMPLEXITY.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Files analyzed: {len(rows)}")
    print(f"Report at {out.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
