"""Dead-code reference scan.

For each `class`/`struct`/`enum`/`interface` declared in the project's runtime
assemblies:

  1. Count how many OTHER files in the project reference its name as a token.
  2. If the count is zero AND the file is the only declaration AND the type
     is `public`/`internal` (i.e. reachable from outside the file), emit a
     candidate.

This is a static filter — generics with type parameters, self-references
(constructor chaining), and reflection-based activation produce false
negatives. The output is `docs/DEAD_CODE_CANDIDATES.md`.
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ASSETS = REPO_ROOT / "Assets"
DOCS = REPO_ROOT / "docs"
DOCS.mkdir(exist_ok=True)

PROD_DIRS = [ASSETS / "Scripts", ASSETS / "Editor", ASSETS / "Plugins", ASSETS / "Tests"]

# Each csproj under the root is a "module" — only count references from a
# different module than the declaration's module.
CSPROJS = [
    p for p in REPO_ROOT.glob("*.csproj")
]

# Maps a .cs file → its containing csproj's name (e.g. "PoFootball.Systems").
# The Scripts/ structure is Assets/Scripts/<ModuleName>/<sub?>/*.cs, so we
# derive the module name from the first folder level under Scripts/.
def _module_of(cs_path: Path) -> str:
    try:
        rel = cs_path.relative_to(ASSETS / "Scripts")
    except ValueError:
        return "unknown"
    parts = rel.parts
    if len(parts) < 2:
        return "unknown"
    return parts[0]


MODULE_OWNERS: dict[str, str] = {}
for csproj in CSPROJS:
    text = csproj.read_text(encoding="utf-8", errors="ignore")
    for m in re.finditer(r"<Compile Include=\"([^\"]+\.cs)\"", text):
        path = (REPO_ROOT / m.group(1)).resolve()
        if path.exists():
            MODULE_OWNERS[str(path)] = csproj.stem

# Final fallback: every .cs file under Assets/Modules is in PoFootball.Whatever
# for each module name.
for csproj in CSPROJS:
    module = csproj.stem
    # Walk all matching subfolders by checking the actual content.
    text = csproj.read_text(encoding="utf-8", errors="ignore")
    for m in re.finditer(r"<Compile Include=\"([^\"]+\.cs)\"", text):
        path = (REPO_ROOT / m.group(1)).resolve()
        if path.exists():
            MODULE_OWNERS[str(path)] = module


def collect_declarations() -> list[tuple[str, Path, str]]:
    """Return (TypeName, FilePath, Module) for every type declaration."""
    out: list[tuple[str, Path, str]] = []
    seen: set[str] = set()
    pattern = re.compile(r"\b(?:public|internal|private|protected)?\s+(?:static|sealed|abstract|partial)?\s+(?:class|struct|enum|interface|record)\s+([A-Z][A-Za-z0-9_]+)")
    for root in PROD_DIRS:
        if not root.exists():
            continue
        for cs in root.rglob("*.cs"):
            try:
                text = cs.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            for m in pattern.finditer(text):
                name = m.group(1)
                if name in seen:
                    continue
                seen.add(name)
                module = MODULE_OWNERS.get(str(cs.resolve()), "unknown")
                out.append((name, cs, module))
    return out


def collect_all_source() -> list[Path]:
    out: list[Path] = []
    for root in PROD_DIRS:
        if not root.exists():
            continue
        out.extend(root.rglob("*.cs"))
    return out


def count_references(name: str, sources: list[Path]) -> int:
    """Total number of references to `name` outside its own declaration file."""
    pattern = re.compile(r"\b" + re.escape(name) + r"\b")
    total = 0
    for path in sources:
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        # Strip the declaration line itself — a class with no uses in any
        # OTHER file still has its own declaration line.
        stripped = re.sub(pattern, "", text, count=1)
        total += len(pattern.findall(stripped))
    return total


def main() -> int:
    declarations = collect_declarations()
    sources = collect_all_source()
    print(f"Declarations: {len(declarations)}")
    print(f"Sources: {len(sources)}")

    candidates: list[tuple[str, Path, str, int]] = []

    for name, path, module in declarations:
        refs = count_references(name, sources)
        if refs == 0:
            candidates.append((name, path, module, refs))

    print(f"Candidates with zero references: {len(candidates)}")

    lines = [
        "# Dead-Code Candidates",
        "",
        "_Generated by Tools/audit_dead_code.py — reference-based, not behavior-based. Review by hand._",
        "",
        "Each row is a type whose declaration file is the ONLY file in the project "
        "that even names the type as a token. Generics in constraints, reflection, "
        "and factory registration are unobserved by this filter; the output is a "
        "starting list, not a verdict.",
        "",
        "| Type | File | Module |",
        "|------|------|--------|",
    ]
    for name, path, module, _ in sorted(candidates, key=lambda x: (x[2], x[0])):
        rel = path.relative_to(REPO_ROOT)
        lines.append(f"| `{name}` | `{rel}` | {module} |")

    out = DOCS / "DEAD_CODE_CANDIDATES.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Report written to {out.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
